### ISSUE TITLE
Make referenced schema paths links

### ISSUE THREAD

**Issue by jasikpark** [JulianCataldo/remark-lint-frontmatter-schema#14]
It'd be great if you could click through to the schema that is complaining about your YAML:

<img width="854" alt="image" src="https://user-images.githubusercontent.com/10626596/191862058-c9ecb541-81c7-445f-b1cc-85e438c960d8.png">
^ I want to click on `Schema path: ...`

**Comment by JulianCataldo** [comment]
Indeed.

I'm gonna add some prefix:
- `./`
- `file:///./`
- or full absolute path in the very last resort.

So VS Code and random CLI app (iTerm…) can pick them up to CMD + click.


Thx!

**Comment by JulianCataldo** [comment]
Interesting finding:
It's not possible at all to customize the "problem" hint overlay / peek tray, as you could with the JS / TS Doc hints you get from IntelliSense.

A TS Doc hint example (unrelated):
![Screenshot 2022-09-23 at 21 08 46](https://user-images.githubusercontent.com/603498/192040158-bf9967cf-33f1-4800-95f6-afb272ae4e08.png)

A "Problem" hint:
![Screenshot 2022-09-23 at 20 30 24](https://user-images.githubusercontent.com/603498/192033783-f9281880-2f1f-4c3c-8266-17d0bef09bec.png)

A "Problem" peek tray:
![Screenshot 2022-09-23 at 21 06 35](https://user-images.githubusercontent.com/603498/192039776-a178e836-93f6-44c6-9b72-2280b25ada07.png)

As you can see, no Markdown or `file:///` support unfortunately. It stays plain text.

However, during this, I found that the hash was messing the path in CLI output,
so at least, I've corrected this, it's now clickable.

![image](https://user-images.githubusercontent.com/603498/192039918-76eeb486-5590-4586-995e-4ca0bf0047df.png)
