### ISSUE TITLE
`correct-creative-work.md` fails remark-lint though it should pass according to the name

### ISSUE THREAD

**Issue by jasikpark** [JulianCataldo/remark-lint-frontmatter-schema#15]
https://github.com/JulianCataldo/remark-lint-frontmatter-schema/blob/master/demo/content/correct-creative-work.md fails to lint with success

**Comment by JulianCataldo** [comment]
You're right lol.
I was in need of more errors at some point, so I've thrown them in the "correct" file, which is totally misleading.
I'm gonna put more dummy files alongside, some good, some bad.

Thx for pointing this out
