### ISSUE TITLE
VSCode extension Marketplace availability 

### ISSUE THREAD

**Issue by matulkum** [JulianCataldo/remark-lint-frontmatter-schema#24]
Hey, thanks a lot for sharing this.

Are there any plans to make the vscode extension available on the vscode marketplace? Background is I would like to install this extension in the vscode web version which is used on Github. I think the only way to install extensions there is through the official marketplace, right?

**Comment by JulianCataldo** [comment]
Hello :)

This lint rule (also qualified as a "remark plugin") is in fact loaded by the **remark** VS Code extension:
https://marketplace.visualstudio.com/items?itemName=unifiedjs.vscode-remark

I don't know the specifics of GitHub VS Code web version though, sorry ;).
