### ISSUE TITLE
Security issue in a dependency: @apidevtools/json-schema-ref-parser

### ISSUE THREAD

**Issue by robinwhittleton** [JulianCataldo/remark-lint-frontmatter-schema#30]
There’s a [“high severity” security issue](https://github.com/advisories/GHSA-5f97-h2c2-826q) in the version of [@apidevtools/json-schema-ref-parser](https://github.com/APIDevTools/json-schema-ref-parser) we’re using (11.1.0). This is fixed in 11.2.0; the latest version is 11.6.4.

I’d be happy to PR a update for this if you’d like, but I’ll leave that up to you.

**Comment by JulianCataldo** [comment]
Hello! Sorry for not responding earlier, I missed that.

Thank you for noticing and for the PR, I'll review this ASAP.

**Comment by robinwhittleton** [comment]
No problem, it was easy enough to pin an override in my system in the mean time! Thanks for providing remark-lint-frontmatter-schema in the first place.

**Comment by sbaechler** [comment]
@JulianCataldo Could you please create a new release with this fix? The current 3.15.4 still contains the vulnerable dependency.

**Comment by JulianCataldo** [comment]
CI is broken. I'll take a look
